repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: check-added-large-files
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
    -   id: forbid-tabs
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285
    hooks:
    - id: ruff
      args: [ '--fix', '--exit-non-zero-on-fix']
-   repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      args: ['-iii', '-ll']
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2
    hooks:
    -   id: pycln
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports

# TODO: update pre-commit configs before pushing
