version: '3'

services:
  web:
    build: .
    env_file:
      - ./library_mgmt/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - db_network

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - db_network

  db:
    image: postgres:12.2
    env_file:
      - ./database.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: on-failure
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  postgres_data:
