# Generated by Django 4.2.2 on 2024-04-07 10:48
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_reservation_circulation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="books",
            old_name="id",
            new_name="book_id",
        ),
        migrations.RenameField(
            model_name="members",
            old_name="id",
            new_name="member_id",
        ),
    ]
