# Generated by Django 4.2.2 on 2024-04-07 11:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_rename_id_books_book_id_rename_id_members_member_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="members",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="deleted_at",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reserved_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterIndexTogether(
            name="circulation",
            index_together={("book", "member", "status")},
        ),
        migrations.RemoveField(
            model_name="circulation",
            name="deleted_at",
        ),
    ]
